### ISSUE TITLE
Does not work with the code generator

### ISSUE THREAD

**Issue by tomitrescak** [enra-GmbH/graphql-codegen-ariadne#5]
Config:

```
overwrite: true
schema: "schema.graphql"
# documents: "**/*.graphql"
generates:
  graphql_types.py:
    plugins:
      - "@enra-gmbh/graphql-codegen-ariadne
```

output

```
(.venv)  ✘ ✝  Github/python-graphql/python-gql   main±  pnpm gql

> @ gql /Users/30031005/Github/python-graphql/python-gql
> graphql-codegen --config codegen.yml

✔ Parse Configuration
⚠ Generate outputs
  ❯ Generate graphql_types.py
    ✔ Load GraphQL schemas
    ✔ Load GraphQL documents
    ✖ visitFn.call is not a function
```
